# Generated by Django 5.2.4 on 2025-08-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('template1', 'Professional Blue'), ('template2', 'Modern Red'), ('template3', 'Creative Green'), ('template4', 'Minimalist Black'), ('template5', 'Minimalist white')], default='template1', max_length=50),
        ),
    ]
